blank_issues_enabled: false
contact_links:
  - name: Discord server
    about: Come chat with the community!
    url: https://discord.gg/akJDeVaxnB
  - name: Documentation
    url: https://kedro.readthedocs.io/en/stable/
    about: To learn more about how Kedro works
  - name: Case studies, articles and video tutorials
    url: https://github.com/kedro-org/kedro-community
    about: Community-generated content, project examples and video tutorials
